### ISSUE TITLE
The lack of lateral connections

### ISSUE THREAD

**Issue by jropen** [xilaili/AOGNet#5]
Thanks for the exciting work. However, I haven't found the operation of lateral connection from the code, as described by horizontal connections in pink in Fig. 1 in the paper. Has this version of the code not been implemented yet? Thanks!

**Comment by xbm626** [comment]
Hi, The new code is available at https://github.com/iVMCL/AOGNets

**Comment by xilaili** [comment]
Hi, The new code is available at https://github.com/iVMCL/AOGNets
